cscript //B //Nologo %1 %2 "__STANDARD_LOG_FILE_APPENDER__" "..\\logs\\rms"
cscript //B //Nologo %1 %2 "__STANDARD_TIME_PROBE_APPENDER__" "..\\logs\\timeprobe"
cscript //B //Nologo %1 %2 "__STANDARD_MEDIA_FOLDER__" "../media"
cscript //B //Nologo %1 %2 "__STANDARD_CONFIG_PERSISTANCE_FILE__" "..\\config\\pushPullSetup.xml"
cscript //B //Nologo %1 %2 "__STANDARD_AUTH_PERSISTANCE_FILE__" "..\\config\\auth.xml"
cscript //B //Nologo %1 %2 "__STANDARD_CONN_LIMITS_PERSISTANCE_FILE__" "..\\config\\connlimits.xml"
cscript //B //Nologo %1 %2 "__STANDARD_BW_LIMITS_PERSISTANCE_FILE__" "..\\config\\bandwidthlimits.xml"
cscript //B //Nologo %1 %2 "__STANDARD_INGEST_POINTS_PERSISTANCE_FILE__" "..\\config\\ingestpoints.xml"
cscript //B //Nologo %1 %2 "__STANDARD_AUTO_DASH_FOLDER__" "..\\rms-webroot"
cscript //B //Nologo %1 %2 "__STANDARD_AUTO_HLS_FOLDER__" "..\\rms-webroot"
cscript //B //Nologo %1 %2 "__STANDARD_AUTO_HDS_FOLDER__" "..\\rms-webroot"
cscript //B //Nologo %1 %2 "__STANDARD_AUTO_MSS_FOLDER__" "..\\rms-webroot"
cscript //B //Nologo %1 %2 "__STANDARD_RTMP_USERS_FILE__" "..\\config\\users.lua"
cscript //B //Nologo %1 %2 "__STANDARD_RTSP_USERS_FILE__" "..\\config\\users.lua"
cscript //B //Nologo %1 %2 "__STANDARD_EVENT_FILE_APPENDER__" "..\\logs\\events.txt"
cscript //B //Nologo %1 %2 "__STANDARD_TRANSCODER_SCRIPT__" "..\\rmsTranscoder.bat"
cscript //B //Nologo %1 %2 "__STANDARD_MP4WRITER_BIN__" "..\\rms-mp4writer.exe"
cscript //B //Nologo %1 %2 "__RMS_AVCONV_BIN__" "..\rms-avconv.exe"
cscript //B //Nologo %1 %2 "__RMS_AVCONV_PRESETS__" "..\rms-avconv-presets"
cscript //B //Nologo %1 %2 "__STANDARD_WEBSERVER_LOG_FILE_APPENDER__" "..\\logs\\rms-webserver"
cscript //B //Nologo %1 %2 "__STANDARD_WEBROOT_FOLDER__" "..\\rms-webroot"
cscript //B //Nologo %1 %2 "__STANDARD_WHITELIST_FILE__" "..\\config\\whitelist.txt"
cscript //B //Nologo %1 %2 "__STANDARD_BLACKLIST_FILE__" "..\\config\\blacklist.txt"
cscript //B //Nologo %1 %2 "__STANDARD_SERVERKEY_FILE__" "..\\config\\server.key"
cscript //B //Nologo %1 %2 "__STANDARD_SERVERCERT_FILE__" "..\\config\\server.cert"
cscript //B //Nologo %1 %2 "--\[\[remove([\s\S]*?)remove\]\]--\n" ""
cscript //B //Nologo %1 %2 "daemon=false," "-- daemon=false,"
cscript //B //Nologo %1 %2 "instancesCount=-1," "-- instancesCount=-1,"

