#!/bin/sh
##########################################################################
# If not stated otherwise in this file or this component's LICENSE
# file the following copyright and licenses apply:
#
# Copyright 2019 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#########################################################################
set -e

RMSUSER=rmsd
RMSGROUP=rmsd

testError ()
{
	if [ "$?" -ne "0" ]
	then
		echo $1
		exit 1
	fi
}


createUserAndGroup ()
{
	if ! getent group $RMSGROUP >/dev/null
	then
		echo adding group $RMSGROUP
		groupadd $RMSGROUP
		testError "Unable to create group $RMSGROUP"
	fi

	if ! getent passwd $RMSUSER >/dev/null
	then
		echo adding user $RMSUSER
		useradd -c "RDKC Media Server Daemon" -g $RMSGROUP -r -N -s /usr/sbin/nologin $RMSUSER
	fi
}

applyPermissions ()
{
	chown -R $RMSUSER:$RMSGROUP /var/rms-webroot
}

case "$1" in
	configure)
		createUserAndGroup
		applyPermissions
		#wget -q -O - http://apt.insertdomainhere.com/example.gpg.key|apt-key add - >/dev/null
		;;
esac

exit 0
